services:
  backend:
    image: ${BACKEND_IMAGE}
    container_name: cinereads-backend
    env_file:
      - .env                 # created on EC2 by ./fetch_env.sh
    environment:
      UVICORN_APP: "app.main:app"
    # keep backend internal in prod (no public port)
    # ports:
    #   - "8000:8000"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-fsS", "http://localhost:8000/health"]
      interval: 30s
      timeout: 5s
      retries: 3

  frontend:
    image: ${FRONTEND_IMAGE}
    container_name: cinereads-frontend
    depends_on:
      backend:
        condition: service_healthy
    ports:
      - "80:80"              # public entry
    restart: unless-stopped
