services:
  backend:
    build:
      context: .
      dockerfile: docker/Dockerfile.backend
    container_name: cinereads-backend
    env_file:
      - backend/.env
    environment:
      UVICORN_APP: "app.main:app"
    ports:
      - "8000:8000"
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:8000/health"]
      interval: 30s
      timeout: 5s
      retries: 3

  frontend:
    build:
      context: .
      dockerfile: docker/Dockerfile.frontend
    container_name: cinereads-frontend
    depends_on:
      - backend
    ports:
      - "80:80"
