name: CI (Review-1 scaffold)
on:
  push:
    branches: [ "main", "devops/*" ]
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Show tree
        run: |
          echo "Repo ready for CI/CD"
          ls -la
